"""fourth Migration

Revision ID: 16443e634b65
Revises: c7b7c7549a2f
Create Date: 2020-12-10 09:37:07.796770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16443e634b65'
down_revision = 'c7b7c7549a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_category', table_name='posts')
    op.create_index(op.f('ix_posts_category'), 'posts', ['category'], unique=False)
    op.add_column('users', sa.Column('image_pic_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_pic_path')
    op.drop_index(op.f('ix_posts_category'), table_name='posts')
    op.create_index('ix_posts_category', 'posts', ['category'], unique=True)
    # ### end Alembic commands ###
